name: 'File Sync'
description: 'Github Action to sync files across repositories'
author: 'kbrashears5 and mauriciodou'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  REPOSITORIES:
    description: 'Github repositories to sync files to. Optionally provide a branch with @branchName after the repo name. Default is master'
    required: true
  FILES:
    description: 'Files to sync to repositories'
    required: true
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true
  DESTINATION_BRANCH:
    description: 'Destination branch to commit the files in destination repos. Defaults to automation'
    required: false
    default: 'automation'
  TERRASERVICE:
    description: 'Name of the specific terraservice being moved with the action. Defaults to none'
    required: false
    default: 'none'

runs:
  using: 'docker'
  image: 'Dockerfile'